In [56]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler


df_train = pd.read_csv('train.csv') #35156
df_test = pd.read_csv('test.csv') #34844

In [57]:
df_test['Weather'] = np.zeros(len(df_test))
train_end_idx = len(df_train) #35156

#1:1:2
#train:0~17577 #val:17578~35155

In [58]:
X_val = df_train[17578:35156]

In [59]:
X_val = X_val.reset_index()

In [60]:
y_val = X_val[['Weather']]

In [61]:
X_Loc = X_val[['Loc']]

In [62]:
X_val = X_val.drop(columns=['Date','Loc','NightWindDir','DayWindDir','WindDir','Weather','index'])

In [63]:

from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=3)

X_val = imputer.fit_transform(X_val)

In [64]:
real_data = pd.DataFrame(X_val,columns=["TempLow","TempHigh","Steaming","Sun","WindSpeed","DayWindSpeed","NightWindSpeed","DayHumidity","NightHumidity","DayPressure","NightPressure","DayCloud","NightCloud","DayTemp","NightTemp","RISK_MM"])
real_data

,TempLow,TempHigh,Steaming,Sun,WindSpeed,DayWindSpeed,NightWindSpeed,DayHumidity,NightHumidity,DayPressure,NightPressure,DayCloud,NightCloud,DayTemp,NightTemp,RISK_MM
0,23.8,31.8,6.933333,5.931076,45.000000,17.000000,7.000000,66.444513,53.164555,1008.400000,1006.700000,8.000000,8.000000,28.8,28.200000,8.6
1,10.9,25.0,5.694960,7.993227,35.000000,17.000000,9.000000,35.799452,61.442809,1021.800000,1018.500000,4.167266,4.278120,15.0,23.200000,0.2
2,19.6,32.4,7.400000,11.600000,30.000000,16.666667,19.666667,46.668269,57.556633,1016.700000,1014.433333,1.000000,3.000000,23.3,28.266667,0.0
3,17.7,23.9,5.694960,7.993227,34.333333,7.000000,24.000000,66.677593,52.237676,1016.300000,1014.533333,4.167266,4.278120,22.7,23.000000,0.0
4,1.4,12.2,5.694960,7.828818,19.000000,11.000000,7.000000,68.774282,69.128241,1038.000000,1035.900000,5.000000,7.000000,5.0,11.700000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17573,21.4,29.5,6.600000,12.100000,28.000000,14.666667,15.000000,53.740315,56.027329,1018.100000,1014.033333,3.000000,2.000000,26.9,28.233333,0.0
17574,16.4,20.0,5.694960,6.664409,46.000000,7.000000,35.000000,81.517289,50.510598,1029.300000,1024.000000,3.000000,1.000000,17.7,18.500000,0.0
17575,8.7,29.7,5.694960,7.993227,33.000000,0.000000,9.000000,25.812760,64.041921,1017.989513,1014.600000,4.167266,4.278120,15.4,25.833333,0.0
17576,10.2,18.7,5.694960,7.993227,63.000000,31.000000,13.000000,52.608538,63.263941,1026.600000,1024.900000,6.000000,4.278120,12.2,17.400000,0.0
17577,9.3,21.6,5.263307,7.993227,48.000000,13.000000,28.000000,57.749757,73.954408,1010.233333,1009.400000,4.167266,3.185414,15.9,20.100000,0.0

In [65]:
#沒有Train的資料
from sklearn.preprocessing import MinMaxScaler
X_train = np.load("NotNML_X_train.npy")
scaler = MinMaxScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_val = scaler.transform(X_val)
X_val = pd.DataFrame(X_val, columns=["TempLow","TempHigh","Steaming","Sun","WindSpeed","DayWindSpeed","NightWindSpeed","DayHumidity","NightHumidity","DayPressure","NightPressure","DayCloud","NightCloud","DayTemp","NightTemp","RISK_MM"])

In [66]:
X_val

,TempLow,TempHigh,Steaming,Sun,WindSpeed,DayWindSpeed,NightWindSpeed,DayHumidity,NightHumidity,DayPressure,NightPressure,DayCloud,NightCloud,DayTemp,NightTemp,RISK_MM
0,0.804749,0.702970,0.096030,0.414761,0.308943,0.229730,0.089744,0.661779,0.468484,0.420863,0.478964,1.000000,1.000000,0.751092,0.670124,0.045503
1,0.464380,0.568317,0.078878,0.558967,0.227642,0.229730,0.115385,0.352894,0.562431,0.661871,0.669903,0.520908,0.534765,0.449782,0.566390,0.001058
2,0.693931,0.714851,0.102493,0.811189,0.186992,0.225225,0.252137,0.462445,0.518328,0.570144,0.604099,0.125000,0.375000,0.631004,0.671508,0.000000
3,0.643799,0.546535,0.078878,0.558967,0.222222,0.094595,0.307692,0.664128,0.457966,0.562950,0.605717,0.520908,0.534765,0.617904,0.562241,0.000000
4,0.213720,0.314851,0.078878,0.547470,0.097561,0.148649,0.089744,0.685262,0.649649,0.953237,0.951456,0.625000,0.875000,0.231441,0.327801,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17573,0.741425,0.657426,0.091413,0.846154,0.170732,0.198198,0.192308,0.533728,0.500973,0.595324,0.597627,0.375000,0.250000,0.709607,0.670816,0.000000
17574,0.609499,0.469307,0.078878,0.466043,0.317073,0.094595,0.448718,0.813704,0.438366,0.796763,0.758900,0.375000,0.125000,0.508734,0.468880,0.000000
17575,0.406332,0.661386,0.078878,0.558967,0.211382,0.000000,0.115385,0.252233,0.591927,0.593337,0.606796,0.520908,0.534765,0.458515,0.621024,0.000000
17576,0.445910,0.443564,0.078878,0.558967,0.455285,0.418919,0.166667,0.522320,0.583098,0.748201,0.773463,0.750000,0.534765,0.388646,0.446058,0.000000
17577,0.422164,0.500990,0.072899,0.558967,0.333333,0.175676,0.358974,0.574141,0.704420,0.453837,0.522654,0.520908,0.398177,0.469432,0.502075,0.000000

In [67]:
X_val['Loc'] = X_Loc
X_val['Weather'] = y_val

In [68]:
X_val

,TempLow,TempHigh,Steaming,Sun,WindSpeed,DayWindSpeed,NightWindSpeed,DayHumidity,NightHumidity,DayPressure,NightPressure,DayCloud,NightCloud,DayTemp,NightTemp,RISK_MM,Loc,Weather
0,0.804749,0.702970,0.096030,0.414761,0.308943,0.229730,0.089744,0.661779,0.468484,0.420863,0.478964,1.000000,1.000000,0.751092,0.670124,0.045503,Cairns,1
1,0.464380,0.568317,0.078878,0.558967,0.227642,0.229730,0.115385,0.352894,0.562431,0.661871,0.669903,0.520908,0.534765,0.449782,0.566390,0.001058,Launceston,0
2,0.693931,0.714851,0.102493,0.811189,0.186992,0.225225,0.252137,0.462445,0.518328,0.570144,0.604099,0.125000,0.375000,0.631004,0.671508,0.000000,Moree,0
3,0.643799,0.546535,0.078878,0.558967,0.222222,0.094595,0.307692,0.664128,0.457966,0.562950,0.605717,0.520908,0.534765,0.617904,0.562241,0.000000,Wollongong,0
4,0.213720,0.314851,0.078878,0.547470,0.097561,0.148649,0.089744,0.685262,0.649649,0.953237,0.951456,0.625000,0.875000,0.231441,0.327801,0.000000,MelbourneAirport,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17573,0.741425,0.657426,0.091413,0.846154,0.170732,0.198198,0.192308,0.533728,0.500973,0.595324,0.597627,0.375000,0.250000,0.709607,0.670816,0.000000,NaN,0
17574,0.609499,0.469307,0.078878,0.466043,0.317073,0.094595,0.448718,0.813704,0.438366,0.796763,0.758900,0.375000,0.125000,0.508734,0.468880,0.000000,Wollongong,0
17575,0.406332,0.661386,0.078878,0.558967,0.211382,0.000000,0.115385,0.252233,0.591927,0.593337,0.606796,0.520908,0.534765,0.458515,0.621024,0.000000,Tuggeranong,0
17576,0.445910,0.443564,0.078878,0.558967,0.455285,0.418919,0.166667,0.522320,0.583098,0.748201,0.773463,0.750000,0.534765,0.388646,0.446058,0.000000,Ballarat,0
17577,0.422164,0.500990,0.072899,0.558967,0.333333,0.175676,0.358974,0.574141,0.704420,0.453837,0.522654,0.520908,0.398177,0.469432,0.502075,0.000000,NaN,0

In [69]:
X_val = X_val.dropna()

In [70]:
Rainy = X_val[X_val['Weather']==0].sample(40)

In [71]:
Sunny = X_val[X_val['Weather']==1].sample(40)

In [72]:
data = pd.concat([Rainy,Sunny])
data

,TempLow,TempHigh,Steaming,Sun,WindSpeed,DayWindSpeed,NightWindSpeed,DayHumidity,NightHumidity,DayPressure,NightPressure,DayCloud,NightCloud,DayTemp,NightTemp,RISK_MM,Loc,Weather
5662,0.571489,0.552475,0.096953,0.860140,0.276423,0.202703,0.243590,0.506814,0.536481,0.625899,0.668285,0.750000,0.125000,0.530568,0.564315,0.000000,MelbourneAirport,0
690,0.386983,0.405941,0.024931,0.223776,0.138211,0.175676,0.192308,0.667560,0.669235,0.742806,0.805825,0.875000,0.875000,0.434498,0.479253,0.000000,SydneyAirport,0
9960,0.403694,0.524752,0.078878,0.558967,0.260163,0.225225,0.282051,0.431144,0.661651,0.587735,0.597087,0.520908,0.875000,0.445415,0.558091,0.000000,Albury,0
14120,0.722955,0.651485,0.094183,0.612896,0.260163,0.202703,0.192308,0.582775,0.408713,0.586331,0.644013,0.500000,0.375000,0.700873,0.672199,0.000353,Brisbane,0
11630,0.762533,0.704950,0.078878,0.558967,0.292683,0.256757,0.307692,0.690342,0.196308,0.550959,0.594391,1.000000,0.534765,0.740175,0.580913,0.003175,Wollongong,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8351,0.820580,0.837624,0.146814,0.720122,0.300813,0.027027,0.307692,0.488355,0.595600,0.433453,0.423948,0.500000,0.375000,0.757642,0.769710,0.000000,Katherine,1
15685,0.562005,0.544554,0.038781,0.558967,0.509485,0.378378,0.384615,0.379273,0.698723,0.501799,0.577670,0.256969,0.219922,0.449782,0.483402,0.034921,Canberra,1
5167,0.683377,0.641584,0.132964,0.223776,0.260163,0.121622,0.141026,0.599353,0.735373,0.559353,0.584142,1.000000,0.875000,0.545852,0.659751,0.002469,Williamtown,1
9422,0.525066,0.617162,0.078878,0.558967,0.078591,0.000000,0.115385,0.593601,0.788499,0.594142,0.620808,0.875000,0.375000,0.550218,0.614108,0.000000,Newcastle,1
1922,0.767810,0.629703,0.180055,0.528980,0.273713,0.270270,0.358974,0.806772,0.528559,0.404676,0.484898,0.875000,1.000000,0.672489,0.647994,0.030688,AliceSprings,1

In [73]:
sample_Loc = data[['Loc']]
sample_Weather = data[['Weather']]

In [74]:
data = data.drop(columns=['Loc','Weather'])

In [75]:
data

,TempLow,TempHigh,Steaming,Sun,WindSpeed,DayWindSpeed,NightWindSpeed,DayHumidity,NightHumidity,DayPressure,NightPressure,DayCloud,NightCloud,DayTemp,NightTemp,RISK_MM
5662,0.571489,0.552475,0.096953,0.860140,0.276423,0.202703,0.243590,0.506814,0.536481,0.625899,0.668285,0.750000,0.125000,0.530568,0.564315,0.000000
690,0.386983,0.405941,0.024931,0.223776,0.138211,0.175676,0.192308,0.667560,0.669235,0.742806,0.805825,0.875000,0.875000,0.434498,0.479253,0.000000
9960,0.403694,0.524752,0.078878,0.558967,0.260163,0.225225,0.282051,0.431144,0.661651,0.587735,0.597087,0.520908,0.875000,0.445415,0.558091,0.000000
14120,0.722955,0.651485,0.094183,0.612896,0.260163,0.202703,0.192308,0.582775,0.408713,0.586331,0.644013,0.500000,0.375000,0.700873,0.672199,0.000353
11630,0.762533,0.704950,0.078878,0.558967,0.292683,0.256757,0.307692,0.690342,0.196308,0.550959,0.594391,1.000000,0.534765,0.740175,0.580913,0.003175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8351,0.820580,0.837624,0.146814,0.720122,0.300813,0.027027,0.307692,0.488355,0.595600,0.433453,0.423948,0.500000,0.375000,0.757642,0.769710,0.000000
15685,0.562005,0.544554,0.038781,0.558967,0.509485,0.378378,0.384615,0.379273,0.698723,0.501799,0.577670,0.256969,0.219922,0.449782,0.483402,0.034921
5167,0.683377,0.641584,0.132964,0.223776,0.260163,0.121622,0.141026,0.599353,0.735373,0.559353,0.584142,1.000000,0.875000,0.545852,0.659751,0.002469
9422,0.525066,0.617162,0.078878,0.558967,0.078591,0.000000,0.115385,0.593601,0.788499,0.594142,0.620808,0.875000,0.375000,0.550218,0.614108,0.000000
1922,0.767810,0.629703,0.180055,0.528980,0.273713,0.270270,0.358974,0.806772,0.528559,0.404676,0.484898,0.875000,1.000000,0.672489,0.647994,0.030688

In [76]:
import joblib
model = joblib.load('Weather_model')
y_pred_decision = model.predict(data)
y_pred_decision

C:\Anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but AdaBoostClassifier was fitted without feature names
  warnings.warn(
C:\Anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MLPClassifier was fitted without feature names
  warnings.warn(
C:\Anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MLPClassifier was fitted without feature names
  warnings.warn(

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1.])

In [77]:
#real_data把跟data重複的索引取出
result_df = real_data.loc[data.index]
result_df

,TempLow,TempHigh,Steaming,Sun,WindSpeed,DayWindSpeed,NightWindSpeed,DayHumidity,NightHumidity,DayPressure,NightPressure,DayCloud,NightCloud,DayTemp,NightTemp,RISK_MM
5662,14.959425,24.200000,7.00000,12.300000,41.000000,15.000000,19.0,51.070177,59.156246,1019.800000,1018.400000,6.000000,1.000000,18.7,23.100000,0.000000
690,7.966667,16.800000,1.80000,3.200000,24.000000,13.000000,15.0,67.018077,70.854075,1026.300000,1026.900000,7.000000,7.000000,14.3,19.000000,0.000000
9960,8.600000,22.800000,5.69496,7.993227,39.000000,16.666667,22.0,43.562818,70.185763,1017.678090,1014.000000,4.167266,7.000000,14.8,22.800000,0.000000
14120,20.700000,29.200000,6.80000,8.764409,39.000000,15.000000,15.0,58.606419,47.897705,1017.600000,1016.900000,4.000000,3.000000,26.5,28.300000,0.066667
11630,22.200000,31.900000,5.69496,7.993227,43.000000,19.000000,24.0,69.278287,29.181246,1015.633333,1013.833333,8.000000,4.278120,28.3,23.900000,0.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8351,24.400000,38.600000,10.60000,10.297742,44.000000,2.000000,24.0,49.238832,64.365583,1009.100000,1003.300000,4.000000,3.000000,29.1,33.000000,0.000000
15685,14.600000,23.800000,2.80000,7.993227,69.666667,28.000000,30.0,38.416631,73.452466,1012.900000,1012.800000,2.055755,1.759373,15.0,19.200000,6.600000
5167,19.200000,28.700000,9.60000,3.200000,39.000000,9.000000,11.0,60.251116,76.681905,1016.100000,1013.200000,8.000000,7.000000,19.4,27.700000,0.466667
9422,13.200000,27.466667,5.69496,7.993227,16.666667,0.000000,9.0,59.680444,81.363251,1018.034270,1015.465952,7.000000,3.000000,19.6,25.500000,0.000000
1922,22.400000,28.100000,13.00000,7.564409,40.666667,20.000000,28.0,80.829566,58.458115,1007.500000,1007.066667,7.000000,8.000000,25.2,27.133333,5.800000

In [78]:
result_df['Loc'] = sample_Loc
result_df['Weather'] = sample_Weather
result_df['Guess'] = y_pred_decision

In [79]:
result_df

,TempLow,TempHigh,Steaming,Sun,WindSpeed,DayWindSpeed,NightWindSpeed,DayHumidity,NightHumidity,DayPressure,NightPressure,DayCloud,NightCloud,DayTemp,NightTemp,RISK_MM,Loc,Weather,Guess
5662,14.959425,24.200000,7.00000,12.300000,41.000000,15.000000,19.0,51.070177,59.156246,1019.800000,1018.400000,6.000000,1.000000,18.7,23.100000,0.000000,MelbourneAirport,0,0.0
690,7.966667,16.800000,1.80000,3.200000,24.000000,13.000000,15.0,67.018077,70.854075,1026.300000,1026.900000,7.000000,7.000000,14.3,19.000000,0.000000,SydneyAirport,0,0.0
9960,8.600000,22.800000,5.69496,7.993227,39.000000,16.666667,22.0,43.562818,70.185763,1017.678090,1014.000000,4.167266,7.000000,14.8,22.800000,0.000000,Albury,0,0.0
14120,20.700000,29.200000,6.80000,8.764409,39.000000,15.000000,15.0,58.606419,47.897705,1017.600000,1016.900000,4.000000,3.000000,26.5,28.300000,0.066667,Brisbane,0,0.0
11630,22.200000,31.900000,5.69496,7.993227,43.000000,19.000000,24.0,69.278287,29.181246,1015.633333,1013.833333,8.000000,4.278120,28.3,23.900000,0.600000,Wollongong,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8351,24.400000,38.600000,10.60000,10.297742,44.000000,2.000000,24.0,49.238832,64.365583,1009.100000,1003.300000,4.000000,3.000000,29.1,33.000000,0.000000,Katherine,1,0.0
15685,14.600000,23.800000,2.80000,7.993227,69.666667,28.000000,30.0,38.416631,73.452466,1012.900000,1012.800000,2.055755,1.759373,15.0,19.200000,6.600000,Canberra,1,0.0
5167,19.200000,28.700000,9.60000,3.200000,39.000000,9.000000,11.0,60.251116,76.681905,1016.100000,1013.200000,8.000000,7.000000,19.4,27.700000,0.466667,Williamtown,1,1.0
9422,13.200000,27.466667,5.69496,7.993227,16.666667,0.000000,9.0,59.680444,81.363251,1018.034270,1015.465952,7.000000,3.000000,19.6,25.500000,0.000000,Newcastle,1,0.0
1922,22.400000,28.100000,13.00000,7.564409,40.666667,20.000000,28.0,80.829566,58.458115,1007.500000,1007.066667,7.000000,8.000000,25.2,27.133333,5.800000,AliceSprings,1,1.0

In [84]:

from sklearn.metrics import accuracy_score, f1_score


#predict
y_pred_decision = model.predict(data)

Y_val = result_df['Weather'].to_numpy()
print('Accuracy: %f' % accuracy_score(Y_val, y_pred_decision))
print('f1-score: %f' % f1_score(Y_val, y_pred_decision))

Accuracy: 0.750000
f1-score: 0.722222

C:\Anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but AdaBoostClassifier was fitted without feature names
  warnings.warn(
C:\Anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MLPClassifier was fitted without feature names
  warnings.warn(
C:\Anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MLPClassifier was fitted without feature names
  warnings.warn(

In [85]:
result_df.to_csv('result_df.csv',  index_label = 'Id')